#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Swift\Foundation\Console\ServeCommand;
use Symfony\Component\Console\Application;

define('BASE_PATH', realpath(__DIR__ . '/'));

$app = new Application();

// register commands
$app->add(new ServeCommand());
$commands = glob(app_path('Console/Commands/*.php'));
foreach ($commands as $command) {
    $bool = preg_match('/(app\/Console\/Commands\/.+?)\.php/', $command, $matches);
    if ($bool !== false && isset($matches[1])) {
        $command = str_replace('/', '\\', ucfirst($matches[1]));
        $app->add(new $command());
    }
}

$app->run();