<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Flame\Routing\Route;

// Route start
Route::group('/api/v1/admin', function () {
    // 创建文章接口
    Route::post('/article', [\App\Bundles\Article\Controllers\Admin\ArticleController::class, 'index']);
    // 通过手机号码登录
    Route::post('/admin/auth/login', [\App\Bundles\Auth\Controllers\Admin\AuthController::class, 'login']);
    // 钉钉内部应用免登
    Route::post('/dingTalk/login', [\App\Bundles\Auth\Controllers\Admin\DingTalkController::class, 'login']);
    // 钉钉扫码登录
    Route::post('/dingTalk/scan', [\App\Bundles\Auth\Controllers\Admin\DingTalkController::class, 'scan']);
    // 管理控制台
    Route::post('/admin', [\App\Bundles\System\Controllers\Admin\IndexController::class, 'index']);
    // 用户列表
    Route::post('/user/index', [\App\Bundles\User\Controllers\Admin\UserController::class, 'index']);
    // 创建用户接口
    Route::post('/user/create', [\App\Bundles\User\Controllers\Admin\UserController::class, 'create']);
});
// end
